In [107]:
import pandas as pd

In [108]:
df = pd.read_pickle("rated_reviews.gzip")

In [110]:
df = df.drop(["_id"], axis=1)
df.head(5)

,title,author,movie,rating,date,review,helpful
0,W domach z betonu,Anna Bielak,Melasa (2012),3,12/11/2014 15:12,"""Melasa"" Carlosa Lechugi jest porównywana do ""...",NaN
1,Dramat bez bohatera,Bartosz Staszczyszyn,Mój biegun (2013),2,24/10/2013 00:00,"W ""Moim biegunie"" mnóstwo jest ładnych obrazkó...",NaN
2,Zemsta hitów,Jakub Popielecki,Avengers: Koniec gry (2019),7,24/04/2019 00:30,"Siedem lat po premierze pierwszych ""Avengers"" ...",NaN
3,Waga piórkowa,Michał Walkiewicz,Underdog (2019),5,14/01/2019 15:03,"Jesteśmy w obskurnej hotelowej toalecie, gdzie...",NaN
4,Złap króliczka,Dorota Kostrzewa,Miss marca (2009),5,15/07/2009 00:00,"Kto ma większego pecha od chłopaka, który za k...",NaN

In [99]:
df.describe()

,title,author,movie,rating,date,review,helpful
count,11027,9738,11027,11027,11027,11027,7007
unique,10696,1463,6297,10,6093,10995,99
top,Zmarnowany potencjał,Marcin Pietrzyk,Mroczny Rycerz (2008),7,02/01/2008 00:00,,50%
freq,7,1090,27,2265,38,33,285

In [100]:
df = df.astype({'rating': 'int32'})
df.dtypes

title      object
author     object
movie      object
rating      int32
date       object
review     object
helpful    object
dtype: object

In [101]:
def add_sentiment():
    """
    Adds a sentiment class to the dataset based on the rating given by the reviewer.
    """
    def determine_sentiment(row):
        if row['rating'] in [1, 2, 3]:
            return "negative"
        elif row['rating'] in [4, 5, 6]:
            return "neutral"
        elif row['rating'] in [7, 8, 9, 10]:
            return "positive"
            
    df['sentiment'] = df.apply(lambda row: determine_sentiment(row), axis=1)

In [102]:
add_sentiment()

In [103]:
df.head(15)

,title,author,movie,rating,date,review,helpful,sentiment
0,W domach z betonu,Anna Bielak,Melasa (2012),3,12/11/2014 15:12,"""Melasa"" Carlosa Lechugi jest porównywana do ""...",NaN,negative
1,Dramat bez bohatera,Bartosz Staszczyszyn,Mój biegun (2013),2,24/10/2013 00:00,"W ""Moim biegunie"" mnóstwo jest ładnych obrazkó...",NaN,negative
2,Zemsta hitów,Jakub Popielecki,Avengers: Koniec gry (2019),7,24/04/2019 00:30,"Siedem lat po premierze pierwszych ""Avengers"" ...",NaN,positive
3,Waga piórkowa,Michał Walkiewicz,Underdog (2019),5,14/01/2019 15:03,"Jesteśmy w obskurnej hotelowej toalecie, gdzie...",NaN,neutral
4,Złap króliczka,Dorota Kostrzewa,Miss marca (2009),5,15/07/2009 00:00,"Kto ma większego pecha od chłopaka, który za k...",NaN,neutral
5,Prawo Murphy'ego,Michał Walkiewicz,Love (2015),5,22/05/2015 13:17,Zaczyna się obrazem leżącej na łóżku i wzajemn...,NaN,neutral
6,Striptiz na przedmieściach,Jakub Popielecki,Popołudniowa igraszka (2013),7,25/10/2013 00:00,Reżyserka-debiutantka Jill Soloway już w pierw...,NaN,positive
7,Camera obscura,Marcin Pietrzyk,Świt (2015),10,01/04/2017 10:46,"Wejście ""Świtu"" do kin to powód do świętowania...",NaN,positive
8,Melancholia cukiernika,Marcin Stachowicz,Kwiat wiśni i czerwona fasola (2015),7,04/08/2016 12:43,An – bo taki jest oryginalny tytuł filmu Naomi...,NaN,positive
9,Kabaret starszych panów,Łukasz Muszyński,Niezniszczalni (2010),5,19/08/2010 00:00,"Sylvester Stallone ma 64 lata na karku, ale me...",NaN,neutral
10,Dyskretny urok prostytucji,Michał Walkiewicz,Sponsoring (2011),7,06/02/2012 00:00,"Człowiek miewa natręctwa, reżyser – obsesje. P...",NaN,positive
11,Życie to nie bajka,Dorota Kostrzewa,Telenowela (2006),6,31/03/2009 00:00,"Przewrotnie ""Telenowela"" w reżyserii debiutują...",NaN,neutral
12,Precz z maczyzmem,Adam Kruk,La tercera orilla (2014),7,14/02/2014 00:00,Nastoletni Nicolás nie mówi za wiele. Zajmuje ...,NaN,positive
13,Wojownicy Spandeksu,Marcin Dąbkowski,Power Rangers (2017),6,24/03/2017 12:08,"Końcówka lat 90. Kilkuletni ja, przebrany w ob...",NaN,neutral
14,Grać czy być,Marcin Pietrzyk,Jesteś tam? (2010),6,10/10/2010 00:00,"Holender David Verbeek w filmie ""Jesteś tam?"" ...",NaN,neutral

In [104]:
df.set_index("movie", inplace=True)

In [106]:
df.loc["Zodiak (2007)"]

,title,author,rating,date,review,helpful,sentiment
movie,,,,,,,
Zodiak (2007),Zbrodnicza układanka,Marcin Pietrzyk,7,13/06/2007 00:00,Jest 1 sierpnia 1969 roku. Do redakcji trzech ...,NaN,positive
Zodiak (2007),Niewiarygodnie klimatyczny film,Midgardsorm,9,26/11/2010 00:00,"Tak - ""Siedem"" ma mroczny i ponury klimat. Ale...",82%,positive
Zodiak (2007),Konfrontacja z gatunkowymi przyzwyczajeniami,eon_blue,9,28/06/2007 00:00,"Nazwisko Davida Finchera, pomimo mocnej pozycj...",49%,positive

In [ ]:
df.loc[df["sentiment"].isna()]